### ISSUE TITLE
有一個bug反饋一下

### ISSUE THREAD

**Issue by jinbasex** [HSSLC/kc-generator#1]
生成的mobi文件會導致kindle翻頁的操作相反
導致以下結果
1 原本kindle 在屏幕向左滑動 是上一頁  向右滑動是下一頁 但是該腳本生成的mobi文件是相反的
2 原本kindle屏幕被分成左右個半邊點擊左半邊是上一頁 右半邊是下一頁，腳本生成的mobi 變成屏幕左邊四分之三的區域是上一頁，右邊四分之一是下一頁

最後再次感謝您的付出。謝謝

**Comment by HSSLC** [comment]
README中有提到如何修改生成出來的檔案的翻頁方向，因為主要是生成右翻漫畫而將預設調成左滑下一頁，如果需要可以在生成的時候自己調整設定。
而我kindle使用至今無論何種書本，翻頁都是下一頁方向的約五分之四是下一頁，上一頁方向的五分之一是上一頁，沒有碰到異常的情況，可能會需要更多資訊來參考判斷。

**Comment by jinbasex** [comment]
非常感謝回復，我會嘗試去調整方向，那就是四分之一點擊是沒辦法解決嗎？
真的非常感謝您的回復，謝謝。

**Comment by HSSLC** [comment]
我認為的kindle翻頁都是這樣，如果右翻的話就是左右相反，但比例相同。
![](https://www.dummies.com/wp-content/uploads/366175.image0.jpg)

**Comment by jinbasex** [comment]
> 我認為的kindle翻頁都是這樣，如果右翻的話就是左右相反，但比例相同。 ![](https://camo.githubusercontent.com/9a75c640e80d9946487b7aef0313cbd6e02e75d661b36bb44d085dc9aa0fe638/68747470733a2f2f7777772e64756d6d6965732e636f6d2f77702d636f6e74656e742f75706c6f6164732f3336363137352e696d616765302e6a7067)
是這樣的沒錯 我其他mobi 都是這樣翻頁 不知道為什麼打開新作的mobi。。。。。。等會，我明白原因出在哪了 設置json 相反即可  麻煩您了  不好意思
